# Generated by Django 5.2.8 on 2025-11-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the project', null=True, upload_to='projects/'),
        ),
    ]
